### ISSUE TITLE
Swapchain の backbuffer を LLGI.Texture でラップして公開する

### ISSUE THREAD

**Issue by lriki** [altseed/LLGI#24]
キャプチャの API で任意のバッファから読み取れるようにするため、Swapchain の backbuffer を、LLGI.Texture でラップして公開するような API を実装する。

次のように使えるようにしたい。

```cpp
auto renderPass = graphics->GetCurrentScreen(color, true);
auto texture = renderPass->GetColorBuffer(0);
auto data = graphics->CaptureRenderTarget(texture);
```

**Comment by wistnki** [comment]
https://github.com/altseed/LLGI/commit/767f2c4acfe66318cbfab535954aa72974592eb3
